#!/usr/bin/env bash
# Commands to Installs nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

# testing nginx configuration
sudo nginx -t
sudo service nginx reload
