#!/usr/bin/env bash
# Configuring web-01 to have an HTTP response header

# To update packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "Hello world!" | sudo tee /var/www/html/index.html

# Performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Afeezope permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#creating a custom (404) error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#test for syntax errors
sudo nginx -t

# restart after making the changes
sudo service nginx restart
