#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy config. file to distribute requests using roundrobin algorithm

echo '
frontend  feesoconnect.tech
        bind 0:80
        default_backend feesoconnect.tech_backend

backend feesoconnect.tech_backend
        balance roundrobin
        server 215001-web-01 35.153.57.107:80
        server 215001-web-02 107.23.177.92:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
