#!/usr/bin/env bash
# This bash script create RSA key pair
# ssh-keygen:command to generate; -b (bits):4096; -P(passphrase):betty; -f(path to store the key): ~/.ssh/school
ssh-keygen -t rsa -b 4096 -P betty -f school
